<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>osu.EzRealmSync.AppModel</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\osu.Game.EzRealmSync\osu.Game.EzRealmSync.csproj">
      <AdditionalProperties>UseLocalOsuLibs=$(UseLocalOsuLibs)</AdditionalProperties>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Localization\Strings.resx" />
    <EmbeddedResource Update="Localization\Strings.zh-Hans.resx" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ez2lazer.Framework" Version="2026.528.1-ez2lazer" />
  </ItemGroup>
</Project>
