<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>osu.EzRealmSync.AppModel</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\osu.Game.EzRealmSync\osu.Game.EzRealmSync.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ppy.osu.Framework" Version="2025.1008.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Localization\Strings.resx" />
    <EmbeddedResource Update="Localization\Strings.zh-Hans.resx" />
  </ItemGroup>
</Project>
