<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>osu.Game.EzRealmSync.OfficialWrite</RootNamespace>
    <AssemblyName>EzRealmSync.OfficialWrite</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\osu.Game.EzRealmSync.Contracts\osu.Game.EzRealmSync.Contracts.csproj" />
    <ProjectReference Include="..\osu.Game.EzRealmSync.OfficialSchema\osu.Game.EzRealmSync.OfficialSchema.csproj" />
  </ItemGroup>
</Project>
