<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Project">
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>osu.EzRealmSync</RootNamespace>
    <AssemblyName>EzRealmSync</AssemblyName>
    <Description>独立 Ez Realm 双库同步工具（纯 osu.Framework UI）。</Description>
    <UseWindowsForms>true</UseWindowsForms>
    <DefineConstants Condition="$([MSBuild]::IsOSPlatform('Windows'))">$(DefineConstants);WINDOWS</DefineConstants>
  </PropertyGroup>
  <PropertyGroup>
    <StartupObject>osu.EzRealmSync.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup Label="Project References">
    <ProjectReference Include="..\osu.Game.EzRealmSync\osu.Game.EzRealmSync.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Using Remove="System.Drawing"/>
  </ItemGroup>

  <ItemGroup Label="Framework">
    <PackageReference Include="ppy.osu.Framework" Version="2025.1008.0"/>
    <PackageReference Include="ppy.osu.Framework.NativeLibs" Version="2025.806.0-nativelibs"/>
    <PackageReference Include="SixLabors.Fonts" Version="2.0.7"/>
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.4"/>
  </ItemGroup>
</Project>
