<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <UseLocalOsuLibs Condition="'$(UseLocalOsuLibs)' == ''">false</UseLocalOsuLibs>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>osu.Game.EzRealmSync.Tests</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup Condition="'$(UseLocalOsuLibs)' == 'true'">
    <Reference Include="$(EzRealmSyncLibDir)\osu.Game.dll">
      <HintPath>$(EzRealmSyncLibDir)\osu.Game.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <PackageReference Include="Realm" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseLocalOsuLibs)' != 'true'">
    <PackageReference Include="ez2lazer.Game" />
    <PackageReference Include="ez2lazer.Game.Resources">
      <ExcludeAssets>all</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Realm" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\osu.Game.EzRealmSync\osu.Game.EzRealmSync.csproj">
      <AdditionalProperties>UseLocalOsuLibs=$(UseLocalOsuLibs)</AdditionalProperties>
    </ProjectReference>
    <ProjectReference Include="..\osu.EzRealmSync.AppModel\osu.EzRealmSync.AppModel.csproj">
      <AdditionalProperties>UseLocalOsuLibs=$(UseLocalOsuLibs)</AdditionalProperties>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <None Include="TestResources\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
