<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <UseLocalOsuLibs Condition="'$(UseLocalOsuLibs)' == ''">false</UseLocalOsuLibs>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>osu.Game.EzRealmSync.Tests</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup Condition="'$(UseLocalOsuLibs)' == 'true'">
    <Reference Include="$(EzRealmSyncLibDir)\osu.Game.dll">
      <HintPath>$(EzRealmSyncLibDir)\osu.Game.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <PackageReference Include="Realm" Version="$(RealmPackageVersion)" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseLocalOsuLibs)' != 'true'">
    <PackageReference Include="ez2lazer.Game" Version="$(Ez2LazerGameVersion)" />
    <PackageReference Include="Realm" Version="$(RealmPackageVersion)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
    <PackageReference Include="NUnit" Version="4.6.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\osu.Game.EzRealmSync\osu.Game.EzRealmSync.csproj">
      <AdditionalProperties>UseLocalOsuLibs=$(UseLocalOsuLibs)</AdditionalProperties>
    </ProjectReference>
    <ProjectReference Include="..\osu.EzRealmSync.AppModel\osu.EzRealmSync.AppModel.csproj">
      <AdditionalProperties>UseLocalOsuLibs=$(UseLocalOsuLibs)</AdditionalProperties>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <None Include="TestResources\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
